### ISSUE TITLE
*.admin.controller.php 구조 재정비 필요

### ISSUE THREAD

**Issue by largeden** [NuriCms/core#10]
*.admin.controller.php의 역할대로 모순이 발생하지 않도록 manager 접근으로 permission을 재정비해야한다고 생각합니다.

member 모듈을 예로 설명하면,

member.admin.controller.php 파일안에 기능들은 admin에서만 동작하도록 형태를 취하고 있지만 관리자체크를 하지 않고 있습니다. 최근 csrf 보안이슈때문에 임시적으로 is_admin체크를 올려놨지만 본래대로라면 권한체크는 module.xml에서 permission으로 정의해야하고 init()를 통해 csrf를 지정했어야합니다.

**Comment by misol** [comment]
admin.view.php 도 마찬가지

**Comment by largeden** [comment]
옳소!! :p

**Comment by largeden** [comment]
정리해야할 사항을 이곳에 정리해뒀으니 참고하시기 바랍니다. 문제가 없다면 내용대로 진행하고자 합니다.
https://docs.google.com/document/d/1S45L8KCCucTyup8v0po-gZ3_i9usDghrYvsRy0Hdimc/

**Comment by largeden** [comment]
https://github.com/NuriCms/core/commit/6eb575069eb7f91983ca74610cfe3725a500027e

**Comment by misol** [comment]
이 부분 완전 찬성입니다!!
