### ISSUE TITLE
resend_auth_mail.html 파일 누락

### ISSUE THREAD

**Issue by largeden** [NuriCms/core#12]
dispMemberResendAuthMail에 reset_mail.html, resend_auth_mail.html이 정의되어있지만 최신 코어에 실제 파일이 없네요.

http://code.google.com/p/xe-core/issues/detail?id=3568

역시 sejin7940님께서...

**Comment by misol** [comment]
act=dispMemberFindAccount 에 해당 기능이 통합된 것 같아요.

**Comment by largeden** [comment]
제가 확인 당시엔 소스에 저 파일이 지정되어있더라고요.(어느파일이었는지 잊어먹음)

**Comment by misol** [comment]
소스에 있긴 한데... 저 부분으로 접속하면 대체된 페이지로 redirect 하는건 어떤가요?

**Comment by largeden** [comment]
음... 우선 누락된 파일을 보충한 뒤에 향후 개선방향으로 가야하는게 맞지 않을까 생각하는데말이죠...
이것은 @skullacy 님에게 맡기죠 ^^ 커밋 부탁드려요~ :)
