### ISSUE TITLE
일부 확장기능 제거 논의

### ISSUE THREAD

**Issue by ghost** [NuriCms/core#13]
별도의 저장소로 분리하여 유지보수를 진행하거나 제거 할 대상을 선정.

예로 point, counter, poll 등의 부가적인 기능들(모듈, 애드온, 위젯)의 분리 운영 및 유지보수 중단 결정.

**Comment by misol** [comment]
Core에서 호환 코드를 모듈로 옮기면서 완전히 독립시킬 수 있을때 하나하나 제거해요. 저장소 분리만 하는건 눈가리고 아웅..

**Comment by ghost** [comment]
@misol 없앨 것(유지보수 중단 및 서드파티 혹은 개인 유지)을 저장소에서 빼버리고, 유지보수를 계속 할 것은 이슈트래킹 분리를 위해 저장소를 분리해두자는 의견입니다.
board 모듈이 밖으로 나와 있는 것처럼요.

**Comment by largeden** [comment]
일단 0.1.0은 버그개선하고 배포하기로 한거니 @bnu 님 의견은 그 다음 버전에서 고려해야할 것 같습니다.
그리고 저는 분리를 한다면 board를 포함해서 분리되는 모듈을 모두 CMS 패키지 형태로 보관했으면 합니다.

CORE
CMS package

이렇게요.

**Comment by ghost** [comment]
네. 당장 처리해야 할 부분이라 생각하지 않아요. 마일스톤을 지정한 이슈가 아닙니다 :)
