### ISSUE TITLE
유연한처리를 위해 moduleHandler()에 Trigger를 추가

### ISSUE THREAD

**Issue by largeden** [NuriCms/core#14]
모듈제작에 있어서 좀 더 유연한 처리가 가능하도록 ModuleHandler()에서 애드온 호출 전에 Trigger를 설치했으면 합니다.

ModuleHandler::triggerCall('moduleHandler', 'before', $this);

// execute addon (before module initialization)
$called_position = 'before_module_init';
$oAddonController = getController('addon');
$addon_file = $oAddonController->getCacheFilePath(Mobile::isFromMobilePhone() ? 'mobile' : 'pc');
@include($addon_file);

애드온 수행 로직에는 모두 애드온 호출 전 Trigger가 선언되어있습니다.
<애드온 호출 전 Trigger가 있음>
before_module_proc
after_module_proc
before_display_content

<애드온 호출 전 Trigger가 없음>
before_module_init

before_module_init는 코어에서도 제일 처음 호출되는 애드온 내용입니다. 이보다 상단에 Trigger를 둠으로써 발생되는 이점은, 모듈자체만으로 코어전체를 컨트롤 하지못해 모듈+애드온으로 제작하던 문제점을 줄일 수 있으며, 모듈과 애드온을 각각별개의 독립적인 역할구조로 나눌 수 있게 해주는 점입니다.

반면, Trigger가 이곳저곳에서 호출되고 있기 때문에 자칫 무분별한 추가는 성능의 저하를 초래할 수 있으니 호출이 필요없는 곳은 제거가 필요합니다.

예) DisplayHandler.class.php
ModuleHandler::triggerCall('display', 'after', $content);

**Comment by largeden** [comment]
추가정도는 0.1.0에 해도 될 것 같은데요...
의견좀...

일단 feature에 머지시켜놓겠습니다.

https://github.com/NuriCms/core/commit/c7e72f3c00df62de29e851a3e3fd9145bc77e059

**Comment by misol** [comment]
저는 찬성이요 :)

**Comment by misol** [comment]
develop 브랜치에 머지 되었습니다.
