### ISSUE TITLE
에디터 기본 파일 업로더에서 플래시 제거.

### ISSUE THREAD

**Issue by misol** [NuriCms/core#18]
가능하면 html 기본 기능으로도 올릴 수 있게 하고, 자바스크립트를 이용해서라도 플래시를 제거하는게 목표.
플래시가 설치되지 않은 PC에서 업로드 할 수 있는 수준이면 됨.
브라우저는 IE, FF 와 그 이상, OS는 Windows 7과 그 이상, 우분투 등 리눅스, iOS 등에서 테스트 해볼것.

**Comment by largeden** [comment]
저도 이거 하려고했는데 @misol 님이 먼저 적으셨군요.
@misol 님께서 적으셨으니 요것은 @misol 님이... :p

그리고 저는 이목을 끌 수 있다는 이유로 이 기능은 0.1.0에서 했으면 좋겠습니다.

**Comment by misol** [comment]
@largeden 전에 이야기가 나왔어서 적은 것일 뿐이에요..

**Comment by misol** [comment]
http://blueimp.github.io/jQuery-File-Upload/ 이거 잘 응용하면 되려나요. 스케치북 스킨에서도 구현이 되어있긴 한데..

**Comment by largeden** [comment]
예제로 올리신곳 좋아보여요 :)

그리고 타 스킨에서 구현했다는건 코어인건드려도 된단 소리니 일단 별도의 에디터스킨을 만들어서 추가해넣는게 안전하겠다 생각합니다.
(jquery업로더용 에디터스킨 추가 배포후 특별히 문제없다면 그때 플레시용 스킨제거)

**Comment by misol** [comment]
==AXISJ==
HTML5를 지원하지 않는 브라우저에는 SWF 업로드,
HTML5를 지원하는 브라우저에는 HTML5 업로드 지원.
