### ISSUE TITLE
제로보드4 호환 코드 제거

### ISSUE THREAD

**Issue by misol** [NuriCms/core#2]
제로보드4와의 호환성을 위한 코드가 Nuri Core 곳곳에 남아있다 제거한다.

**Comment by Eundong** [comment]
4 호환 코드가 남아있었나요????

어디에?.. 처음알았어.

**Comment by misol** [comment]
@Eundong func.inc.php 아랫쪽으로 쭉 내려보세요 ㅋㅋ
아마 지워도 될 것 같아요. 존재를 아는 사람이 거의 없는듯..

**Comment by misol** [comment]
비밀번호 암호화 부분에 zeroboard4 에서 사용하던 mysql password 함수가 있는데, 회원모듈에서만 쓰입니다. 안쓰이면 지우려했는데 쓰이긴 하네요.. 어쩌죠

**Comment by misol** [comment]
이건 0.1.0 한참 뒤에 다시 생각해보는걸로.. 한 내년쯤이나
