### ISSUE TITLE
속도가 많이 걸리는 함수 제거

### ISSUE THREAD

**Issue by misol** [NuriCms/core#22]
eval 은 별로 없는 것 (사실 한군데 정도..) 같은데
@ 가 붙은 함수는 대단히 많습니다. 가능하면 제거해보는게 어떤가요.
is_readable 까지 확인해놓고 @를 붙이는건 좀 너무해보입니다.

str_replace와 다름 없는 구문에 preg_replace를 쓰는 부분도 있어요. 이런 부분을 다듬을 필요가 있습니다.

**Comment by largeden** [comment]
찬성해요.

0.1.0에서 진행해도 될 것 같습니다. :)

**Comment by misol** [comment]
정규식 쓰는 부분과 @ 쓰는 부분을 봤는데, 건드리기 두려운 부분도 있고 해서 여기까지만 할게요.
