### ISSUE TITLE
이름, 카피라이트 변경

### ISSUE THREAD

**Issue by misol** [NuriCms/core#3]
누리 또는 Nuri 로 이름을 변경한다.
NuriCMS
누리CMS
NuriCore
누리 코어
등의 용어를 상황에 맞게 사용한다.

예시 웹 사이트 주소 중 모 프로젝트를 가리키는 주소는 nuricms.org 로 모두 변경한다.

**Comment by largeden** [comment]
소스상 변경을 위해서는 이름과 이메일 주소가 필히 필요하니 대표 이메일 주소를 얼른 정해야겠습니다.

**Comment by ghost** [comment]
copyright 표기를 어떻게 해야 할까요?

```
/**
 * @file ...
 * @author NHN (developers@xpressengine.com)
 * @brief ...
 **/
```

NHN의 카피라이트를 유지하고 추가해야 맞을까요?

```
/**
 * @file ...
 * @author NHN (developers@xpressengine.com)
 * @author NuriCms?? (OOO@nuricms.org)
 * @brief ...
 **/
```

이제보니 author로 표기 할 팀/그룹의 이름이 마땅치 않기도 하네요.
NuriCMS? Nuri?

**Comment by ghost** [comment]
@misol 지금 처리 중인 NHN -> NURI Project로 변경하는 부분은 라이선스 규정에 적절할까요?
LGPL에 카피라이트 표기는 유지하도록 규정되어 있으므로 카피라이트는 변경하지 않도록 해야 할 것 같습니다.

**Comment by misol** [comment]
@bnu author 가 NHN이면, 책임도 NHN이 져야하는 것인가 하는 생각이 들어서 바꾸고 있습니다.
maintainer 로 바꾸고 author 부분을 아예 지울까요?

**Comment by misol** [comment]
@bnu 다음 문서 http://www.xpressengine.com/tip/18997077 에 따르면 될 것 같습니다.

**Comment by ghost** [comment]
@misol "5. Powered by 나 Copyright 문구 삭제해도 되나요?"에서 삭제해도 된다는 것은 레이아웃이나 스킨 구석에 표기되는 것을 가리킵니다. 'Powered by XpressEngine' 또는 'Copyright by {레이아웃 제작자}' 같은 문구 말이죠.

소스코드에 명시된 카피라이트는 다릅니다.
좀 더 자세히 알아봐야겠네요.
LICENSE 파일 또는 index.php 파일등에 LGPL이 안내하고 있는 카피라이트 표기가 되어 있지 않아서 모호하네요.

하지만 일부 라이브러리를 가져다 일부 수정하였다고 `@copyright` 또는 `@author` 문구를 변경하지 않는 것처럼 전체 변경은 맞지 않아 보입니다.

**Comment by ghost** [comment]
각 파일의 처음에 `@author`을 포함하고있는 주석문은 차라리 제거하고 LGPL에서 안내하는 카피라이트 표기를 LICENSE 파일에 NHN(이제는 NAVER)로 표기 후 NURI에서 수정되었음을 안내하는 편이 좋을 것 같습니다.

**Comment by misol** [comment]
@bnu 절충해서 원작자를 표시하고, 현재 작업자를 표시하겠습니다.

**Comment by misol** [comment]
앗! 그런데 제가 마스터에 커밋 하고 있었군요!!;;; ㄷㄷㄷ 다음부턴 조심할게요
