### ISSUE TITLE
member 모듈의 dispMemberAdminConfig 정의에 대하여...

### ISSUE THREAD

**Issue by largeden** [NuriCms/core#30]
&lt;!--action name="dispMemberAdminConfig" type="view" menu_name="userSetting" menu_index="true" /--&gt;

요런 문구가 member 모듈에 들어있으며,

member.admin.view.php에도 함수가 정의되어있습니다.

```
/**
 * Set the default config.
 *
 * @return void
 */
public function dispMemberAdminConfig()
{
    $this->setTemplateFile('default_config');

}
```

주석처리된 이유가 무엇이며 기능의 목적이 무엇인지 아시는분은 설명바랍니다.
(새로운 기능 만들려다가 말았나?)

**Comment by largeden** [comment]
&lt;!--action name="dispMemberAdminConfig" type="view" menu_name="userSetting" menu_index="true" /--&gt;
&lt;action name="dispMemberAdminConfig" type="view" menu_name="userSetting" menu_index="true" /&gt;

이렇게 되어있는거봐서는 그냥 예전 작업내용이 남아있는건가봐요? 삭제??

**Comment by misol** [comment]
사용되고 있는 페이지에요.

**Comment by misol** [comment]
궁금하시면 https://www.nuricms.org/index.php?module=admin&act=dispMemberAdminConfig 이런 식으로 접속해보세요.

**Comment by largeden** [comment]
단순주석이군요.
삭제해야겠어요~
