### ISSUE TITLE
setRequestMethod 기능 추가

### ISSUE THREAD

**Issue by largeden** [NuriCms/core#38]
#37

fileupload를 만들다가 구조적으로 좋지 않은걸 개선하고 있었는데요. 아래와 같은 유형도 대응할 수 있도록 NuriCms에서 처리되면 좋겠다고 생각하여 제안합니다.

기존 요청방식

client(html) -- core -- server(html)
client(json) -- core -- server(json)
client(xml)  -- core -- server(xml)
client(*>js_callback)  -- core -- server(js_callback)

향후 요청방식

client(html) -- core -- server(html)
client(json) -- core -- server(json)
client(xml)  -- core -- server(xml)
client(_>js_callback)  -- core -- server(js_callback)
client(_>json_callback)  -- core -- server(json)
client(*>xml_callback)  -- core -- server(xml)

몇몇 외부 라이브러리의 경우 보통의 GET, POST로 요청을 보내고 서버측으로부터는 JSON, XML으로 받아야 동작하는 경우가 있습니다. 현재 XE가 그런 대응이 없기 때문에 아래처럼 개선하여 param값으로 출력을 헨들링 하면 좋겠다고 생각합니다.

context.class.php
<?php
/**
- Determine request method
  *
- @param string $type Request method. (Optional - GET|POST|XMLRPC|JSON)
- @return void
  */
  function setRequestMethod($type = '')
  {
  is_a($this, 'Context') ? $self = $this : $self = Context::getInstance();
  
  (isset($_GET['xe_js_callback']) && $self->js_callback_func = isset($_GET['xe_js_callback'])) or
      (isset($_POST['xe_js_callback']) && $self->js_callback_func = isset($_POST['xe_js_callback']));
  
  (isset($_GET['xe_json_callback']) && $self->json_callback_func = isset($_GET['xe_json_callback'])) or
      (isset($_POST['xe_json_callback']) && $self->json_callback_func = isset($_POST['xe_json_callback']));
  
  (isset($_GET['xe_xml_callback']) && $self->xml_callback_func = isset($_GET['xe_xml_callback'])) or
      (isset($_POST['xe_xml_callback']) && $self->xml_callback_func = isset($_POST['xe_xml_callback']));
  
  ($type && $self->request_method = $type) or
          (strpos($_SERVER['CONTENT_TYPE'], 'json') && $self->request_method = 'JSON') or
          (isset($GLOBALS['HTTP_RAW_POST_DATA']) && $self->request_method = 'XMLRPC') or
          ($self->js_callback_func && $self->request_method = 'JS_CALLBACK') or
          ($self->json_callback_func && $self->request_method = 'JSON') or
          ($self->xml_callback_func && $self->request_method = 'XMLRPC') or
          ($self->request_method = $_SERVER['REQUEST_METHOD']);
  }

?>

요청은 이렇게 합니다.
var params = {
        mid : current_mid,
        module : 'file',
        act : 'getFileList',
        xe_json_callback: 'xe_json_callback'
    };

exec_xml(
    'file',
    'getFileList',
    params,
    func,response_tags);

**Comment by misol** [comment]
client(>json_callback) -- core -- server(json)
client(*>xml_callback) -- core -- server(xml)
두가지를 추가하는 거군요 :)

**Comment by largeden** [comment]
네!
client(*>json_callback) -- core -- server(json) 오타가 있었군요.
완료 처리하겠습니다!
