### ISSUE TITLE
관리자모드에서 상단이 보이는 바의 처리

### ISSUE THREAD

**Issue by largeden** [NuriCms/core#45]
생각해보니 상단에 한줄로 굵게 들어간게 좀 불편한데요. 요걸 네모난 버튼으로 만들고 마우스오버시 보여지거나 조금 수정하는게 좋을거 같아요.

이를테면 화면 우측구석이 종이접혀놓은 것처럼 디자인해서 마우스대면 다음장 넘길려는듯한 처리...
(이해돼심??)

**Comment by misol** [comment]
피드백 주시면 좋겠어요
