### ISSUE TITLE
PHP 최신버전에서 설치 오류 문제 보고

### ISSUE THREAD

**Issue by kbsbroad** [NuriCms/core#59]
PHP 5.5 대 이상에서 설치시 여전히 빈 오브젝트에 값을 할당하는 오류가 남아있는 듯 합니다. 많은 부분 수정하셔서 없애셨을 것 같은데 아직 남아있네요. xampp 최신버전에서 테스트 했습니다.

설치 설정을 모두 마친후에 발생했구요. 오류 내역은 다음과 같습니다.(중복 라인은 제거했습니다.)

`
Warning: Creating default object from empty value in C:\xampp\htdocs\nuri\modules\file\file.class.php on line 19
Warning: Creating default object from empty value in C:\xampp\htdocs\nuri\modules\poll\poll.class.php on line 19
Warning: Creating default object from empty value in C:\xampp\htdocs\nuri\modules\member\member.class.php on line 114
Warning: Creating default object from empty value in C:\xampp\htdocs\nuri\modules\point\point.class.php on line 22
Warning: Creating default object from empty value in C:\xampp\htdocs\nuri\modules\addon\addon.admin.controller.php on line 232
Warning: Creating default object from empty value in C:\xampp\htdocs\nuri\modules\module\module.controller.php on line 400
Warning: Creating default object from empty value in C:\xampp\htdocs\nuri\modules\install\script\ko.install.php on line 37
Warning: Creating default object from empty value in C:\xampp\htdocs\nuri\modules\install\script\ko.install.php on line 43
Warning: Creating default object from empty value in C:\xampp\htdocs\nuri\modules\install\script\ko.install.php on line 96
Warning: Creating default object from empty value in C:\xampp\htdocs\nuri\modules\install\script\ko.install.php on line 113
Warning: Creating default object from empty value in C:\xampp\htdocs\nuri\files\faceOff\147\ko.cache.php on line 1
`

맨 마지막에 보시면 캐시로 생성되는 파일에도 해당 오류가 있는 듯 합니다.

**Comment by misol** [comment]
오류 보고 감사합니다 :)
